version: '3.8'
services:
  db:
    image: mongo
    restart: always
    volumes:
      - data:/data/db
    networks:
      - mern-app
  api:
    build: ./api
    container_name: booking_server
    ports:
     - "8080:8080" 
    env_file:
     - ./api/.env 
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - mern-app
  client: 
    build: ./client
    container_name: booking_react_app
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - api
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  data:
